cmake_minimum_required(VERSION 3.8)
project(mbot_control)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(std_msgs REQUIRED)
add_executable(mbot_controller src/mbot_controller.cpp)
ament_target_dependencies(mbot_controller rclcpp std_msgs)
install(TARGETS mbot_controller DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY config launch DESTINATION share/${PROJECT_NAME})
ament_package()
